//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiemDanh.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDanh
    {
        public System.DateTime Ngay { get; set; }
        public int MaMon { get; set; }
        public string MaSV { get; set; }
        public bool DiMuon { get; set; }
        public bool DiHoc { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
